In [42]:
import nltk

In [43]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

True

In [44]:
from nltk.tokenize import word_tokenize

text = "Sistem temu kembali adalah teknik yang digunakan dalam perncarian dokumen."

tokens = word_tokenize(text)
print(tokens)

['Sistem', 'temu', 'kembali', 'adalah', 'teknik', 'yang', 'digunakan', 'dalam', 'perncarian', 'dokumen', '.']

In [45]:
text = "Sistem Temu Kembali Informasi Sangat Penting"

lower_text = text.lower()
print(lower_text)

sistem temu kembali informasi sangat penting

In [46]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

text = "Sistem temu kembali informasi adalah teknologi yang sangat penting dalam pencarian dokumen"

tokens = word_tokenize(text.lower())

stop_words = set(stopwords.words('indonesian'))
filtered_tokens = [word for word in tokens if word not in stop_words]

print('Teks Asli:', text)
print('Token Setelah Stopword Removal:', filtered_tokens)

Teks Asli: Sistem temu kembali informasi adalah teknologi yang sangat penting dalam pencarian dokumen
Token Setelah Stopword Removal: ['sistem', 'temu', 'informasi', 'teknologi', 'pencarian', 'dokumen']

In [47]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()
words = ['running', 'runs', 'easily', 'faster']

stemmed_words = [ps.stem(words) for words in words]
print(stemmed_words)

['run', 'run', 'easili', 'faster']

In [48]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# Membuat objek stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

text = 'Pemrograman komputer memerlukan logika dan pemahaman mendalam tentang algoritma'

stemmed_text = stemmer.stem(text)

print('Teks Asli:', text)
print("Steleah Stemming:", stemmed_text)

Teks Asli: Pemrograman komputer memerlukan logika dan pemahaman mendalam tentang algoritma
Steleah Stemming: pemrograman komputer perlu logika dan paham dalam tentang algoritma

In [49]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
words = ['running', 'runs', 'better', 'flies']
lemmatized_words = [lemmatizer.lemmatize(word, pos='v') for word in words]

print(lemmatized_words)

['run', 'run', 'better', 'fly']

In [50]:
import nltk
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('stopwords')

# Teks artikel
text = 'Sistem temu kembali informasi sangat berguna dalam pencarian data dan dokumen. Penggunaan teknologi ini memungkinkan akses cepat dan mudah.'

# 1. Caase Foldling
text = text.lower()

# 2. Tekonisasi
tokens = word_tokenize(text)

# 3. Stopword Removal
stop_words = set(stopwords.words('indonesian'))
filtered_tokens = [word for word in tokens if word not in stop_words and word.isalnum()]

# 4. Stemming
factory = StemmerFactory()
stemmer = factory.create_stemmer()
stemmed_tokens = [stemmer.stem(word) for word in filtered_tokens]

# Hasil Akhir
print('Teks Asli:', text)
print('')
print('Token Setelah Stopword Removal dan Stemming:', stemmed_tokens)

Teks Asli: sistem temu kembali informasi sangat berguna dalam pencarian data dan dokumen. penggunaan teknologi ini memungkinkan akses cepat dan mudah.

Token Setelah Stopword Removal dan Stemming: ['sistem', 'temu', 'informasi', 'guna', 'cari', 'data', 'dokumen', 'guna', 'teknologi', 'akses', 'cepat', 'mudah']

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [51]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import nltk
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [52]:
df = pd.read_excel('datasetweek4stk.xlsx', header=0)

df.head()

                                                data
0  pembukaan daftar wisuda dan pelaksanaan nya le...
1  dalam setahun belakangan ini, pengaksesan KRS ...
2  Assalamualaikum Wr. Wb. yang menjadi salah sat...
3  pak/bu dosen saya mau minta keringanan biaya p...
4  Aduh, cuaca hari ini panas banget ya! Kemarin ...

In [53]:
def clean_lower(lwr):
    lwr = lwr.lower()
    return lwr

In [54]:
df['hasil_casefolding'] = df['data'].apply(clean_lower)
casefolding = pd.DataFrame(df['hasil_casefolding'])
casefolding

                                   hasil_casefolding
0  pembukaan daftar wisuda dan pelaksanaan nya le...
1  dalam setahun belakangan ini, pengaksesan krs ...
2  assalamualaikum wr. wb. yang menjadi salah sat...
3  pak/bu dosen saya mau minta keringanan biaya p...
4  aduh, cuaca hari ini panas banget ya! kemarin ...
5  kemarin malam aku nonton film baru di netflix,...
6  wah, ternyata jadi orang tua itu bukan hal yan...
7  kalau ada yang bilang jadi mahasiswa itu enak,...
8  pagi ini aku harus bangun pagi banget, karena ...
9  weekend kemarin aku pergi ke pantai sama kelua...

In [55]:
stopword = set(stopwords.words('indonesian'))

def clean_stopwords(text):
    text = ' '.join(word for word in text.split() if word not in stopword)
    return text

df['hasil_stopword'] = df['hasil_casefolding'].apply(clean_stopwords)

In [56]:
stopwordremoval = pd.DataFrame(df['hasil_stopword'])

stopwordremoval

                                      hasil_stopword
0  pembukaan daftar wisuda pelaksanaan nya d umum...
1  setahun ini, pengaksesan krs diganti siam (seb...
2  assalamualaikum wr. wb. salah syarat ujian kom...
3  pak/bu dosen keringanan biaya proposional spp ...
4  aduh, cuaca panas banget ya! kemarin aja hujan...
5  kemarin malam nonton film netflix, judulnya tu...
6  wah, orang tua mudah. aja diurus, kerjaan ruma...
7  bilang mahasiswa enak, coba deh rasain sendiri...
8  pagi bangun pagi banget, rapat kantor. semalam...
9  weekend kemarin pergi pantai keluarga. seru ba...

In [57]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def get_stemmed_term(text):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    hasil = stemmer.stem(text)
    return hasil

df['hasil_stemming'] = df['hasil_stopword'].apply(get_stemmed_term)

In [58]:
stemmingSastrawi = pd.DataFrame(df['hasil_stemming'])
stemmingSastrawi

                                      hasil_stemming
0  buka daftar wisuda laksana nya d umum web ub f...
1  tahun ini akses krs ganti siam belum sinergi s...
2  assalamualaikum wr wb salah syarat uji kompre ...
3  pak bu dosen ringan biaya proposional spp soal...
4  aduh cuaca panas banget ya kemarin aja hujan d...
5  kemarin malam nonton film netflix judul tuh de...
6  wah orang tua mudah aja urus kerja rumah nguru...
7  bilang mahasiswa enak coba deh rasain sendiri ...
8  pagi bangun pagi banget rapat kantor malam aja...
9  weekend kemarin pergi pantai keluarga seru ban...

In [59]:
from nltk.tokenize import word_tokenize
def word_tokens(text):
    token = word_tokenize(text)
    return token

df['hasil_tokenisasi'] = df['hasil_stemming'].apply(word_tokens)

In [60]:
tokenkata = pd.DataFrame(df['hasil_tokenisasi'])
tokenkata

                                    hasil_tokenisasi
0  [buka, daftar, wisuda, laksana, nya, d, umum, ...
1  [tahun, ini, akses, krs, ganti, siam, belum, s...
2  [assalamualaikum, wr, wb, salah, syarat, uji, ...
3  [pak, bu, dosen, ringan, biaya, proposional, s...
4  [aduh, cuaca, panas, banget, ya, kemarin, aja,...
5  [kemarin, malam, nonton, film, netflix, judul,...
6  [wah, orang, tua, mudah, aja, urus, kerja, rum...
7  [bilang, mahasiswa, enak, coba, deh, rasain, s...
8  [pagi, bangun, pagi, banget, rapat, kantor, ma...
9  [weekend, kemarin, pergi, pantai, keluarga, se...

In [61]:
teks_Asli = pd.Series(df['data'])
casefolding = pd.Series(df['hasil_casefolding'])
stopwordremoval = pd.Series(df['hasil_stopword'])
stemming = pd.Series(df['hasil_stemming'])
tokenisasi = pd.Series(df['hasil_tokenisasi'])

df = pd.DataFrame({
    'Teks Asli': teks_Asli,
    'Hasil Casefolding': casefolding,
    'Hasil Stopword Removal': stopwordremoval,
    'Hasil Stem': stemming,
    'Hasil Tokenisasi': tokenisasi
})

In [62]:
hasil_pre_pro = df.to_excel('Hasil Pre-Processing Week 4 STK.xlsx', sheet_name='sheet_satu')